# Generated by Django 5.1.4 on 2025-01-15 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('category_id', models.IntegerField()),
                ('image', models.CharField(max_length=2083)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=512)),
                ('desc', models.CharField(max_length=2083)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
